-- MySQL Script generated by MySQL Workbench
-- Sat Dec 28 03:46:02 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SmartParking
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SmartParking
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SmartParking` DEFAULT CHARACTER SET utf8 ;
USE `SmartParking` ;

-- -----------------------------------------------------
-- Table `SmartParking`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SmartParking`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` ENUM("admin", "driver", "manager") NOT NULL,
  PRIMARY KEY (`id`) )
  ;


-- -----------------------------------------------------
-- Table `SmartParking`.`driver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SmartParking`.`driver` (
  `license` VARCHAR(20) NOT NULL,
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id`
    FOREIGN KEY (`id`)
    REFERENCES `SmartParking`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SmartParking`.`parking_lot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SmartParking`.`parking_lot` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `manager_id` INT NULL,
  `lot_name` VARCHAR(45) NOT NULL,
  `location` VARCHAR(255) NOT NULL,
  `capacity` INT NOT NULL,
  `pricing_structure` INT NOT NULL,
  `start_peek_time` INT NULL,
  `end_peek_time` INT NULL,
  `price_multiplier` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `ManagerLotID`
    FOREIGN KEY (`manager_id`)
    REFERENCES `SmartParking`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SmartParking`.`spot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SmartParking`.`spot` (
  `lot_id` INT NOT NULL,
  `spot_id` INT AUTO_INCREMENT,
  `status` ENUM("occupied", "available", "reserved") NOT NULL,
  `type` ENUM("regular", "disabled", "EV") NOT NULL,
  PRIMARY KEY (`spot_id`),
  CONSTRAINT `LotID`
    FOREIGN KEY (`lot_id`)
    REFERENCES `SmartParking`.`parking_lot` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SmartParking`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SmartParking`.`reservation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `spot_id` INT NOT NULL,
  `lot_id` INT NOT NULL,
  `driver_id` INT NOT NULL,
  `reservation_status` ENUM("Accepted", "Rejected", "Pending") NOT NULL,
  `reservation_hours` INT NOT NULL,
  `reservation_time` DATETIME NOT NULL,
  `reservation_fee`  float,
  PRIMARY KEY (`id`),
  CONSTRAINT `Spot`
    FOREIGN KEY (`spot_id`)
    REFERENCES `SmartParking`.`spot` (`spot_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Lot`
    FOREIGN KEY (`lot_id`)
    REFERENCES `SmartParking`.`parking_lot` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Driver`
    FOREIGN KEY (`driver_id`)
    REFERENCES `SmartParking`.`driver` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SmartParking`.`penalities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SmartParking`.`penalities` (
  `reservation_id` INT NOT NULL,
  `penality_fee` FLOAT NULL,
  PRIMARY KEY (`reservation_id`),
  CONSTRAINT `ReservationID`
    FOREIGN KEY (`reservation_id`)
    REFERENCES `SmartParking`.`reservation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;